"""added Member model

Revision ID: 1a01c8f04283
Revises: 88844fce4909
Create Date: 2024-10-30 08:28:28.383913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a01c8f04283'
down_revision: Union[str, None] = '88844fce4909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('userid', sa.BigInteger(), nullable=False),
    sa.Column('ingame', sa.String(), nullable=False),
    sa.Column('server', sa.Integer(), nullable=False),
    sa.Column('has_changed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
